# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
dependencies:
  pre:
    - sudo pip install awsebcli
jobs:
  deploy:
    docker:
      - image: circleci/node:8.9
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -y python-pip libpython-dev
      - run: sudo easy_install --upgrade six
      - run: sudo pip install awsebcli
      - run: eb use Ledgers
      - run: bash ./setup-eb.sh
      - run: cat ~/.aws/config
      - run: eb deploy --verbose
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - staging

